### ISSUE TITLE
Polymer 3 Compat

### ISSUE THREAD

**Issue by shiaoya** [greenyouse/bottom-nav#11]
I looked into how to convert this project to be compatible with Polymer 3 and it seems pretty easy for someone with intimate knowledge of how it works (ie: you, @greenyouse) 
You just gotta use a polymer tool called Modulizer. I'm fairly new to Polymer, so I have no idea how v2 works, only v3. Obviously this doesn't make me the best candidate for updating this project. I would greatly appreciate this project being made compatible with v3! 

Best, Noah

**Comment by greenyouse** [comment]
Sure, I'll give it another shot. I tried upgrading it a couple weeks ago but the Modulizer generated a broken v3 component. I was working through getting it fixed but left it about halfway complete. I'll spend some time this week figuring out how to fix it.

If I run into trouble I'll post something as an update. There's another open ticket #10 for tracking upgrading to Polymer 3 too. I'm going to close this one but feel free to post in the other :)
