### ISSUE TITLE
Polymer 2 or Hybrid

### ISSUE THREAD

**Issue by JaySunSyn** [greenyouse/bottom-nav#7]
Many thanks for this element!

Any plans to port it to hybrid or Polymer 2?

Thanks!

**Comment by greenyouse** [comment]
Thanks for the reminder! This element is long overdue for an update.

I'll start migrating it to polymer 2 right now.

**Comment by greenyouse** [comment]
OK, I added a polymer-2 branch. I'll look at updating the tests and merging it tomorrow.

**Comment by greenyouse** [comment]
@JaySunSyn the polymer 2 version should be all set.

**Comment by JaySunSyn** [comment]
Awesome @greenyouse! Thanks!
